name: civicrm
services:

  civicrm:
    image: ghcr.io/bds-nl/civicrm-fpm:latest
    ports:
    - "8080:8080"
    user: 33:33
    volumes:
    - public:/var/www/html/public
    - private:/var/www/html/private
    - ext:/var/www/html/ext
    depends_on:
    - db

  nginx:
    image: ghcr.io/bds-nl/civicrm-nginx:latest
    network_mode: "service:civicrm"
    volumes:
    - public:/var/www/html/public
    - private:/var/www/html/private
    - ext:/var/www/html/ext
    depends_on:
    - civicrm

  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: civicrm
      MYSQL_USER: civicrm
      MYSQL_PASSWORD: civicrm
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
    - db:/var/lib/mysql

volumes:
  public:
  private:
  ext:
  db:
